---
- hosts: node-1
  gather_facts: false
  tasks:
    - name: get process list
      shell: |
        set -o pipefail
        ps -ef |grep -v grep
      changed_when: false
      register: ret

    - name: print vars
      debug: var=ret
